### ISSUE TITLE
Quick win: Addon hard to find

### ISSUE THREAD

**Issue by ThomDietrich** [jcwillox/hassio-rclone-backup#12]
Hey @jcwillox,
Thanks for this great addon. Has done a great job for a couple of months now.

I want to raise a significant issue that is super easy to solve :) Your addon can't be found via google :D I want to sync my Home Assistant backups to owncloud. Obviously I would google for "Home Assistant backup to owncloud" and end up with big disappointment as there seems to be no addon available 🙃

I think the solution to this issue is very easy: Add the most important storage providers/protocols rclone supports to the top of README.md. Additionally tune the repository description to a more shiny "Home Assistant backup sync to most cloud and remote targets" 

Best!

**Comment by ThomDietrich** [comment]
https://letmegooglethat.com/?q=Home+Assistant+backup+to+owncloud

Still doesn't work. Would you mind copying this into the readme?

**Comment by jcwillox** [comment]
I've added the list of providers to the README so hopefully, that will help.
