### ISSUE TITLE
Provide rclone.conf via yaml config

### ISSUE THREAD

**Issue by ThomDietrich** [jcwillox/hassio-rclone-backup#13]
Hey!
For easy maintenance it is not ideal to have to configure this addon in two areas, through UI supported addon config and an additional `rclone.conf`. I am saying not ideal, because obviously all of us are capable to manage that, however, I wonder if there is a better way?

Did you ever explore ways to provide the content of `rclone.conf` via the yaml config?

Untested. This should pretty much do the trick:

```yaml
schedule: 10 4 * * *
command: sync
sources:
  - /backup
destination: 'hassbackup:'
include:
  - DailyBackup*
# we can also disable google drive trash using flags
flags: 
  - --drive-use-trash=false
config: |
  [google]
  type = drive
  scope = drive
  token = REDACTED
  ; immediately delete backups instead of sending them to the trash
  use_trash = false
  [hassbackup]
  type = crypt
  remote = google:Backup/Home Assistant
  filename_encryption = off
  directory_name_encryption = false
  password = REDACTED
  password2 = REDACTED
```

**Comment by jcwillox** [comment]
I like this idea it would be much more convenient to have it in the UI, the only issue is that rclone wouldn't be able to write to the config, which currently isn't an issue, but could be if we add the rclone web UI. Still probably worth adding this 🤷

**Comment by ThomDietrich** [comment]
Good point and true. I would argue that a user that wants to use the UI doesn't need the `config:` part of the UI, a user that just wants to provide a fixed `rclone.conf` can go the `config:` route.
Pay attention that I did not use the `config_path` keyword from your existing solution. Those two can be mutually exclusive.
Are you going to work on this? I would be happy to provide a PR, but not before end of year ^^

**Comment by jcwillox** [comment]
Haha, only a 10 month turn around, dw I'll be adding this soon. I've just rewritten most of the core in golang, as it actually has a good scheduling library with support for cron-syntax. Won't be much extra effort to add support for this too 👍.

**Comment by jcwillox** [comment]
This is supported as of release [2.0.0](https://github.com/jcwillox/hassio-rclone-backup/releases/tag/2.0.0) 🎉, with the `rclone_config` option.

**Comment by ThomDietrich** [comment]
Great! Thank you

**Comment by ThomDietrich** [comment]
Sorry for the late response! I've just setup a new system with this option and everything works perfectly.

Could you implement one improvement? Would be great if `config_path` is not mandatory, or if `[]` were supported. Currently I need to resort to this:

```yaml
config_path: /config/rclone.conf_not-used
rclone_config: |
  [owncloud]
  type = webdav
```

**Comment by jcwillox** [comment]
Sure it can be changed to optional, however, you shouldn't have to rename `config_path` as it will be overridden when you specify `rclone_config`. Also, this should ideally be a separate feature request as it's easier to track.
