### ISSUE TITLE
rclone config does not exist!

### ISSUE THREAD

**Issue by maxifly** [jcwillox/hassio-rclone-backup#15]
I install addon.
Start it and find error in log file:
[FATAL]: rclone config does not exist!
If this is your first time starting this add-on ensure to create a valid rclone configuration at "/config/rclone.conf"

I must install rclone or simple create rclone config file?

**Comment by jcwillox** [comment]
Yeah at this time you'll need to create the config separately using the rclone commandline tool. The documention gives a brief description of this at the bottom. It's pretty straightforward rclone guides you through most of it.
