### ISSUE TITLE
Error notification

### ISSUE THREAD

**Issue by Vartkat** [jcwillox/hassio-rclone-backup#16]
Hello,

and thanks for the addon. One thing, if the operation fails nothing is alerting user. If possible you should make something that allows to alert user in case of failure. Either directly or just an binary_sensor "rclone failed" so that we can react using either automation or Node Red.

V.

**Comment by jcwillox** [comment]
Add-ons can't really create entities in Home Assistant, but possibly we could send a persistent notification, or maybe even fire an event I'll have to see

**Comment by Vartkat** [comment]
thanks.

**Comment by jcwillox** [comment]
Added in [3.0.0](https://github.com/jcwillox/hassio-rclone-backup/releases/tag/3.0.0).

The addon now sends events to HA, and there's a blueprint for notifications too.
