### ISSUE TITLE
[FR]: Make `config_path` optional

### ISSUE THREAD

**Issue by jcwillox** [jcwillox/hassio-rclone-backup#21]
### Is your feature request related to a problem? Please describe.

https://github.com/jcwillox/hassio-rclone-backup/issues/13#issuecomment-1239321974

### Describe the solution you'd like

Make the `config_path` option, optional.

**Comment by jcwillox** [comment]
Added in [3.0.0](https://github.com/jcwillox/hassio-rclone-backup/releases/tag/3.0.0).

**Comment by ThomDietrich** [comment]
Amazing, thank you!!
