### ISSUE TITLE
Error connecting Google drive 

### ISSUE THREAD

**Issue by Joezi79** [jcwillox/hassio-rclone-backup#24]
### The problem

I have installed RClone Backup and would like to use Google drive for uploading files. Here is my config:

[Google]
type = drive
client_id = xxxx-yyyyyylf4g4ht3c178h2ifmfrfmd0f8.apps.googleusercontent.com
client_secret = xxxx-yyyyyjitl4DUjBJAu6RbVzU8qnc
token = 
scope = 

Unfortunately, I am getting the following error if I am using webgui in home assistant to list files of google drive:

2022/11/24 07:54:27 ERROR : rc: "operations/list": error: drive: failed when making oauth client: failed to create oauth client: empty token found - please run "rclone config reconnect Google:"
2022/11/24 07:54:27 ERROR : rc: "operations/list": error: drive: failed when making oauth client: failed to create oauth client: empty token found - please run "rclone config reconnect Google:"
2022/11/24 07:54:27 ERROR : rc: "operations/list": error: drive: failed when making oauth client: failed to create oauth client: empty token found - please run "rclone config reconnect Google:"
2022/11/24 07:54:30 ERROR : rc: "operations/list": error: drive: failed when making oauth client: failed to create oauth client: empty token found - please run "rclone config reconnect Google:"

How can I run listed rclone command in home assistant. I do not see any terminal.

### What version of Rclone Backup has the issue?

1.95.2

### What version of Home Assistant are you running?

2022.10.5

### What type of installation are you running?

Home Assistant Supervised

### Anything in the logs that might be useful for us?

```python3
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Rclone Backup
 Automatically sync backup to remote locations using rclone
-----------------------------------------------------------
 Add-on version: 3.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (armv7 / raspberrypi4)
 Home Assistant Core: 2022.10.5
 Home Assistant Supervisor: 2022.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
Log level is set to DEBUG
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/init.sh
cont-init: info: /etc/cont-init.d/init.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun rclone (no readiness notification)
services-up: info: copying legacy longrun scheduler (no readiness notification)
s6-rc: info: service legacy-services successfully started
[08:22:42] INFO: Installed rclone version:
[08:22:42] INFO: Starting Rclone Web GUI...
[08:22:42] INFO: rclone v1.59.2
- os/version: alpine 3.16.0
- os/kernel: 5.15.61-v7l (armv7l)
- os/type: linux
- os/arch: arm
- go/version: go1.18.6
- go/linking: static
- go/tags: none
[08:22:42] INFO: Starting Scheduler...
[2022-11-24] [08:22:42] [INFO]: rclone config found
2022/11/24 08:22:42 NOTICE: Serving files from "/usr/share/rclone-webui-react"
2022/11/24 08:22:42 NOTICE: Serving remote control on http://[::]:8099/
2022/11/24 08:22:42 NOTICE: Web GUI is not automatically opening browser. Navigate to http://[::]:8099/ to use.
[2022-11-24] [08:22:42] [INFO]: checking job configs...
[2022-11-24] [08:22:42] [INFO]: scheduled jobs:
10 4 * * * sync "Sync Daily Backups"; /backup -> Google:/Camera
2022/11/24 08:23:47 ERROR : rc: "operations/uploadfile": error: drive: failed when making oauth client: failed to create oauth client: empty token found - please run "rclone config reconnect Google:"
```

**Comment by zaggash** [comment]
Hi,
Your token is empty.
`failed to create oauth client: empty token found`

Did you follow this ?
https://rclone.org/drive/#configuration

**Comment by Joezi79** [comment]
You can
