### ISSUE TITLE
Issue getting pcloud to work

### ISSUE THREAD

**Issue by lbouriez** [jcwillox/hassio-rclone-backup#25]
### The problem

Hello, I am trying to setup the addon following the documentation, I am pretty new to rclone.
My conf is as follow:
```
[pcloud]
type = pcloud
client_id = My_CLIENT_ID
client_secret = MY_CLIENT_SECRET
username = XXX
password = XXX
token = XXX <= Access token that I got from PCloud using postman
use_trash = false

[hassbackup]
type = crypt
remote = pcloud:Backup/Home Assistant
filename_encryption = off
directory_name_encryption = false
password = XX
password2 = XX
```

When I open the gui, if i try to see the conf, I get an error:
![image](https://user-images.githubusercontent.com/4749766/205170970-c4b8c540-40da-4b12-9f98-2b919cea1884.png)

### What version of Rclone Backup has the issue?

3.0.0

### What version of Home Assistant are you running?

2022.11.5

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

2022.11.2

### Example YAML snippet

```yml
- name: Sync Daily Backups
  schedule: 10 4 * * *
  command: sync
  sources:
    - /backup
  include: []
  exclude: []
  flags: {}
  destination: "hassbackup:"
```

### Anything in the logs that might be useful for us?

```python3
10 4 * * * sync "Sync Daily Backups"; /backup -> hassbackup:
2022/12/01 17:13:01 ERROR : rc: "operations/list": error: failed to configure Pcloud: invalid character 'Y' looking for beginning of value
2022/12/01 17:13:14 NOTICE: Make sure your Redirect URL is set to "http://localhost:53682/" in your custom config.
2022/12/01 17:13:14 NOTICE: If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth?state=v9TA12NfpFG5CmQJq3Slxw
2022/12/01 17:13:14 NOTICE: Log in and authorize rclone for access
2022/12/01 17:13:14 NOTICE: Waiting for code...
```

**Comment by lbouriez** [comment]
I tried with OneDrive, getting the same issue :(

**Comment by jcwillox** [comment]
Hmm, well it looks like your config may be invalid try placing double quotes around any strings contain `Y`.

You could also try it with the rclone comma d line separately if you want.

**Comment by lbouriez** [comment]
It doesnt work, when I use the gui, I go in the conf, click on next next and it immediately redirect me to the gui main page. In the log I get this:
![image](https://user-images.githubusercontent.com/4749766/205497699-51d6d7b4-0825-4bb7-aa19-dee962e98ad9.png)
I made this gif to show you the redirect:
![rclone](https://user-images.githubusercontent.com/4749766/205497911-6d971ed6-ee0f-48cb-bd35-f58d11950a34.gif)
Please help

**Comment by lbouriez** [comment]
Hello @jcwillox , could you help me, I really tried everything. As soon as the gui should open a page I get an error notification.
In the log I get that:

2022/12/27 14:38:01 NOTICE: Make sure your Redirect URL is set to "http://localhost:53682/" in your custom config.
2022/12/27 14:38:01 NOTICE: If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth?state=p9uJCOQra3x7

Obviously it doesnt work, this port doesnt seems open and we are using ingress.

Pleeeease help :)

**Comment by PatrickGlesner** [comment]
It works!

I followed [this rclone/pcloud doc](https://rclone.org/pcloud/), installed Rclone on my MacBook, got the token (/!\ format : {{"access_token":"•••••••••••••••••••••••••••","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}} ), configured hassio-rclone-backup and voilà!

I hope you will solve your problem.

Best regards,
Patrick.

**Comment by lbouriez** [comment]
Hello, I didnt update my message but yes, i got it working in a similar way, I was just expecting the gui to make the process simpler...

**Comment by AlecRust** [comment]
@lbouriez would you mind sharing how you worked around this?

**Comment by lbouriez** [comment]
@AlecRust , i didn't use the GUI but the manual setup of rsync. For that I needed to install rsync in my windows machine to generate the token.
1- start the manual setup in the docker container
2- when it asks for the token, go on rsync in your windows machine and generate it
