### ISSUE TITLE
Initial Setup - not possible via GUI due to missing conf files

### ISSUE THREAD

**Issue by dafunkydan** [jcwillox/hassio-rclone-backup#28]
### The problem

After installing, i can't configure Hassio Rclone Backup over GUI. After starting the Addon, it halts due to missing/wrong Configuration / Job (See example Error Log below).

It looks like there needs to be one functioning rsync.conf as well as a matching job, before proceeding to load the Addon.
Trying to work around and create them manually, i can't find detailled Conf/Job Examples to adapt to my Environment, neither on [Hassio-Rclone](https://github.com/jcwillox/hassio-rclone-backup), nor on [RClone](https://rclone.org/gui/) (Command-Line Based Documentation).

Best would be to be able to configure Hassio-Rclone via GUI from Scratch.
If that isn't possible, it would really help to have a Bunch of "Pre-Made" rclone.conf / Jobs, to adapt them. Personally, i would use WebDAV, SMB2/3, maybe Dropbox.

### What version of Rclone Backup has the issue?

3.0.0

### What version of Home Assistant are you running?

Home Assistant 2022.12.9

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

Supervisor 2022.12.1

### Anything in the logs that might be useful for us?

```python3
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Rclone Backup
 Automatically sync backup to remote locations using rclone
-----------------------------------------------------------
 Add-on version: 3.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.12.9
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/init.sh
cont-init: info: /etc/cont-init.d/init.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun rclone (no readiness notification)
services-up: info: copying legacy longrun scheduler (no readiness notification)
s6-rc: info: service legacy-services successfully started
[10:15:44] INFO: Installed rclone version:
[10:15:44] INFO: Starting Rclone Web GUI...
2023/01/22 10:15:44 NOTICE: Serving files from "/usr/share/rclone-webui-react"
2023/01/22 10:15:44 NOTICE: Serving remote control on http://[::]:8099/
2023/01/22 10:15:44 NOTICE: Web GUI is not automatically opening browser. Navigate to http://[::]:8099/ to use.
[10:15:44] INFO: rclone v1.59.2
- os/version: alpine 3.16.0 (64 bit)
- os/kernel: 5.15.76-v8 (aarch64)
- os/type: linux
- os/arch: arm64
- go/version: go1.18.6
- go/linking: static
- go/tags: none
[10:15:44] INFO: Starting Scheduler...
[2023-01-22] [10:15:44] [INFO]: rclone config found
[2023-01-22] [10:15:44] [INFO]: checking job configs...
[2023-01-22] [10:15:44] [FATAL]: remote 'google:' does not exist; configured remotes are [[]]
[09:15:44] WARNING: Halt add-on with exit code 1
s6-rc: info: service legacy-services: stopping
[09:15:44] WARNING: Rclone Web GUI crashed, halting add-on (code: 143)
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by mskudlarski** [comment]
Same, here I even tested on fresh install, same result as on my oryginal HAOS

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Rclone Backup
 Automatically sync backup to remote locations using rclone
-----------------------------------------------------------
 Add-on version: 3.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / qemux86-64)
 Home Assistant Core: 2023.1.7
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/init.sh
cont-init: info: /etc/cont-init.d/init.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun rclone (no readiness notification)
services-up: info: copying legacy longrun scheduler (no readiness notification)
s6-rc: info: service legacy-services successfully started
[17:58:04] INFO: Installed rclone version:
[17:58:04] INFO: Starting Rclone Web GUI...
2023/01/23 17:58:04 NOTICE: Serving files from "/usr/share/rclone-webui-react"
2023/01/23 17:58:04 NOTICE: Serving remote control on http://[::]:8099/
2023/01/23 17:58:04 NOTICE: Web GUI is not automatically opening browser. Navigate to http://[::]:8099/ to use.
[17:58:04] INFO: rclone v1.59.2
- os/version: alpine 3.16.0 (64 bit)
- os/kernel: 5.15.80 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.18.6
- go/linking: static
- go/tags: none
[17:58:04] INFO: Starting Scheduler...
[2023-01-23] [17:58:04] [WARN]: rclone config not found at "/config/rclone.conf"
[2023-01-23] [17:58:04] [INFO]: checking job configs...
[2023-01-23] [17:58:04] [FATAL]: remote 'google:' does not exist; configured remotes are [[]]
[16:58:04] WARNING: Halt add-on with exit code 1
s6-rc: info: service legacy-services: stopping
[16:58:04] WARNING: Rclone Web GUI crashed, halting add-on (code: 143)
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by jcwillox** [comment]
It looks like the issue might actually be the addon config, not rclone, try replacing the list of jobs with `[]`
![image](https://user-images.githubusercontent.com/39120423/215248438-7ac31f53-93cb-4235-b905-ef34fb0dc8bd.png)

**Comment by dafunkydan** [comment]
As simple as. Works, Thanks!
Suggestion: Remove the Sample-Config from the Installation :-)
And Thanks for providing the HA-Addon, really great!

**Comment by dotbanana** [comment]
Where can you find this list of jobs to edit?

**Comment by oooshk** [comment]
thank you!
