### ISSUE TITLE
Rclone Backup crashes on startup

### ISSUE THREAD

**Issue by jimford-sudo** [jcwillox/hassio-rclone-backup#37]
### The problem

Appears to install on my Raspberry Pi docker installation of HA, but log shows that it crashes on starting.

### What version of Rclone Backup has the issue?

1.6.1

### What version of Home Assistant are you running?

2023.7.3

### What type of installation are you running?

Home Assistant Container

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

2023.07.1

### Anything in the logs that might be useful for us?

```python3
[10:46:32] INFO: rclone v1.61.1
- os/version: alpine 3.16.0 (64 bit)
- os/kernel: 6.1.21-v8 (aarch64)
- os/type: linux
- os/arch: arm64
- go/version: go1.19.4
- go/linking: static
- go/tags: none
[10:46:32] INFO: Starting Scheduler...
[2023-07-29] [10:46:32] [WARN]: rclone config not found at "/config/rclone.conf"
[2023-07-29] [10:46:32] [INFO]: checking job configs...
[2023-07-29] [10:46:32] [FATAL]: remote 'google:' does not exist; configured remotes are [[]]
[09:46:32] WARNING: Halt add-on with exit code 1
s6-rc: info: service legacy-services: stopping
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
[09:46:33] WARNING: Rclone Web GUI crashed, halting add-on (code: 143)
```

### Additional information

Using the HA terminal to log into the Raspberry Pi,  <find ./ -name 'rclone*'> didn't find a rclone binary or rclone.conf .

I _could_ create an rclone.conf manually, but there would be no point if there's no binary installed.

**Comment by jimford-sudo** [comment]
It seems that on startup Rclone Backup looks for an existing rclone.conf file containing at least one remote configuration. If the data isn’t there the addon will not start but crash. There is a facility to set up a remote from within its web gui - but if the web gui hasn’t started (because the addon crashed) then it can’t be set up.

I worked round this by using a rclone.conf from another machine, that I had been using. Rclone Backup then started and ran. However, I can’t get the real-time data in the dashboard to update and show.

**Comment by Erudition** [comment]
same as #47

**Comment by Erudition** [comment]
Fix:
https://github.com/jcwillox/hassio-rclone-backup/issues/28#issuecomment-1407300750
