### ISSUE TITLE
Fail backup on S3 bucket

### ISSUE THREAD

**Issue by adbig** [jcwillox/hassio-rclone-backup#4]
Hi,

I use since days your hass-auto-backup add-on. Now I want to sync my backup on my S3 bucket  with hassio-rclone-backup but I think I made a mistake in my configuration. Since your example provide config only for google drive, I don't know where I should provide my S3 bucket name in the add-on config.

Here is my config : 

rclone.conf

```
[hass-backup-test]
provider = AWS
env_auth = false
access_key_id = XXXXXXXXXXXXX
secret_access_key = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
region = eu-west-1
storage_class = STANDARD_IA
```

Add-on config : 

```
schedule: 54 * * * *
command: sync
sources:
  - /backup
destination: hass-backup-test
include: []
exclude: []
flags: []
dry_run: false
config_path: /config/rclone.conf
```

Error I got : 

```
2021/09/11 12:54:00 ERROR : Fatal error received - not attempting retries
2021/09/11 12:54:00 INFO  : 
Transferred:   	          0 / 0 Byte, -, 0 Byte/s, ETA -
Errors:                 1 (fatal error encountered)
Elapsed time:         0.0s
2021/09/11 12:54:00 Failed to sync: can't sync or move files on overlapping remotes
[rclone-backup-rename] Starting at 2021-09-11 12:54:00
[rclone-backup-rename] Renamed 4 backups
[rclone-backup-rename] Finished at 2021-09-11 12:54:00
[rclone-backup] Rclone failed!
[rclone-backup-undo-rename] Starting at 2021-09-11 12:54:00
[rclone-backup-undo-rename] Finished at 2021-09-11 12:54:00
[rclone-backup] Started at 2021-09-11 12:54:00
[rclone-backup] Finished at 2021-09-11 12:54:00
[rclone-backup] Done!
```

Thank you for your help and your efforts to build and maintain these add-ons.

Adrien

**Comment by jcwillox** [comment]
Thanks, the `rclone.conf` file looks fine, but the `destination` must have a `:` and optionally a path (otherwise it'll just save to the root), so it should be `destination: 'hass-backup-test:'`.

It's the same issue you'd have if you tried to list the files in the bucket using the rclone command line

* `rclone lsd google` fails
* `rclone lsd google:` works

It's a bit of a weird quirk with rclone, but the addon should have caught that error.

**Comment by adbig** [comment]
Hello,

I tried  `:`  at the beginning but I had this error :   
`Failed to create file system for "aws:hass-backup-adrien:": didn't find section in config file`.

I clone your repo to debug in local and I found that the error comes from rclone.conf file and it's a bit vicious !

To generate my rclone config, I ran on my computer  `rclone config` command and copy the output of this command in the rclone.conf  file .

But  the output is incomplete !

See the output config : 
```
Edit advanced config? (y/n)
y) Yes
n) No
y/n> n
Remote config
--------------------
[test]
provider = AWS
env_auth = false
access_key_id = XXXXXXXXXXXXXXXXX
secret_access_key = YYYYYYYYYYYYYYYYYYYYYYYYYYYYY
region = eu-west-1
location_constraint = eu-west-1
acl = private
server_side_encryption = AES256
storage_class = STANDARD_IA
--------------------
```

A mandatory line is missing :  `type = s3`

When you edit the config this value suddenly appears : 

```
e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> e
Choose a number from below, or type in an existing value
 1 > hass-backup-adrien
 2 > test
remote> 2
--------------------
[test]
type = s3
provider = AWS
env_auth = false
access_key_id = XXXXXXXXXXXXXXXXX
secret_access_key = YYYYYYYYYYYYYYYYYYYYYYYYYYYYY
region = eu-west-1
location_constraint = eu-west-1
acl = private
server_side_encryption = AES256
storage_class = STANDARD_IA
--------------------
```

Maybe it's interesting to add this info in an AWS example in the README.

Thanks again for your help.

Adrien

**Comment by jcwillox** [comment]
Oh wow how interesting, I've been planning to add a section to the documentation about generating the `rclone.conf` file, I'll definitely mention this in there, although hopefully, users will be able to configure it via the UI once I add support for the Rclone Web GUI.
