### ISSUE TITLE
Error: didn't find backend called "protondrive"

### ISSUE THREAD

**Issue by svalsemey** [jcwillox/hassio-rclone-backup#42]
### The problem

Proton Drive is not supported in the used rclone version (1.61.1).

### What version of Rclone Backup has the issue?

3.0.1

### What version of Home Assistant are you running?

Home Assistant 2023.12.3

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

Supervisor 2023.12.0

### Example YAML snippet

```yml
- name: Sync Daily Backups
  schedule: 10 4 * * *
  command: sync
  sources:
    - /backup
  destination: protondrive:Backup/Home Assistant/
  include: []
  exclude: []
  flags: {}
```

### Anything in the logs that might be useful for us?

```python3
[2023-12-25] [04:10:00] [INFO]: running "Sync Daily Backups"; /backup -> protondrive:Backup/Home Assistant/
[2023-12-25] [04:10:00] [INFO]: renamed 11 backups
2023/12/25 04:10:00 Failed to create file system for "protondrive:Backup/Home Assistant/": didn't find backend called "protondrive"
[2023-12-25] [04:10:00] [ERROR]: failed to run rclone command: exit status 1
2023/12/25 06:34:29 ERROR : rc: "operations/fsinfo": error: didn't find backend called "protondrive"
2023/12/25 06:34:29 ERROR : rc: "operations/list": error: didn't find backend called "protondrive"
```

### Additional information

Need to bump to rclone 1.65.0?

**Comment by jcwillox** [comment]
Thanks, released in https://github.com/jcwillox/hassio-rclone-backup/releases/tag/3.1.0 🎉
