### ISSUE TITLE
Error while mounting unit, FUSE3 not found

### ISSUE THREAD

**Issue by McGiverGim** [jcwillox/hassio-rclone-backup#45]
### The problem

Trying to mount Google Drive as unit, I get this error:
```
2024/01/05 10:21:13 Fatal error: failed to mount FUSE fs: fusermount: exec: "fusermount3": executable file not found in $PATH
```
looking into internet, it seems a bug that happens since version 1.62: https://github.com/rclone/rclone/issues/6844

I've tried to execute a `apk add fuse3` from the bash of the docker, and then all works perfectly. Maybe is a good workaround to add this to the creation of the docker.

### What version of Rclone Backup has the issue?

3.1.0

### What version of Home Assistant are you running?

2024.1.0

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

Supervisor 2023.12.0

### Anything in the logs that might be useful for us?

```python3
2024/01/05 10:21:13 Fatal error: failed to mount FUSE fs: fusermount: exec: "fusermount3": executable file not found in $PATH
```

### Additional information

The PRs that added the FUSE mount were https://github.com/jcwillox/hassio-rclone-backup/pull/44 and https://github.com/jcwillox/hassio-rclone-backup/pull/41 from @jcwillox and @agodet, maybe you have a better solution for this.

**Comment by McGiverGim** [comment]
After adding fuse3, it works, it mounts but I have another problem, but maybe is more a config problem:
- The folder "mounted" inside the docker, is different than the "folder" of the Home Assistant. For example, I mount the "/media/security/rclone" folder to a Google Drive folder, and if I add a file in Home Assistant to this folder, I can't see it in the docker, and the inverse.

Some idea about how to fix this?

**Comment by Wallnusskaese** [comment]
Experiencing the same issue. 

`2024/03/08 21:55:52 ERROR : rc: "mount/mount": error: failed to mount FUSE fs: fusermount: exec: "fusermount3": executable file not found in $PATH`

after apk add fuse3 I only get:

`2024/03/08 22:11:24 mount helper error: fusermount3: fuse device not found, try 'modprobe fuse' first`

any suggestions? LG
