### ISSUE TITLE
Ability to run once on startup

### ISSUE THREAD

**Issue by blancqua** [jcwillox/hassio-rclone-backup#5]
Hi, thanks a lot for this add-on. I've installed it yesterday and works like a charm.

It would be nice to have the ability to start `rclone` when a certain event happens. In my case, I'm using this add-on together with your auto-backup integration. The event I would use is `auto_backup.backup_successful`, meaning that, whenever a backup finishes, please sync using rclone.

Kind regards

**Comment by jcwillox** [comment]
Definitely an interesting idea, but might not be very easy to implement we'd need something that connects to the Home Assistant API and persistently listens for events. Potentially we could add a run on start option then take advantage of the `hassio.addon_restart` to trigger it to sync the backups.

**Comment by blancqua** [comment]
Ahah. Or we can just create an Automation, which triggers the add-on upon that specific event. If we change the add-on to just run rclone once when no "schedule" is provided, and then end, we can then link it to that automation.

A bit like the "Let's Encrypt" add-on which just runs and exits.

What do you think?

Sent from ProtonMail mobile

-------- Oorspronkelijk bericht --------
Aan 4 nov. 2021 06:29, Josh Willox schreef:

**Comment by jcwillox** [comment]
This is supported as of release [2.0.0](https://github.com/jcwillox/hassio-rclone-backup/releases/tag/2.0.0) 🎉.
