### ISSUE TITLE
Cannot use recursing  */ crons

### ISSUE THREAD

**Issue by anto294** [jcwillox/hassio-rclone-backup#59]
### The problem

Hi, if I try to do a sync every 5 minutes for example, it is impossible to save the configuration.

### What version of Rclone Backup has the issue?

3.1.0

### What version of Home Assistant are you running?

24.05

### What type of installation are you running?

HAOS on Proxmox

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

Latest

### Additional information

![immagine](https://github.com/jcwillox/hassio-rclone-backup/assets/10341813/533a238a-705f-4710-afc9-21873572ff99)

**Comment by jcwillox** [comment]
We use https://github.com/go-co-op/gocron to parse and schedule cron expressions, so if they don't support them, I'd recommend filing an issue over there. In that screenshot is the "unable to save" message related to the issue at all?

**Comment by anto294** [comment]
Now I can't tell if it depends on GoCron.
I have now done a cleaner job: rclone installed natively on proxmox, sync from SMB to S3. Performance is superior it seems.

Those who have baremetal haos need this addon though.
