### ISSUE TITLE
Add multiple configurations

### ISSUE THREAD

**Issue by DrahcireD** [jcwillox/hassio-rclone-backup#6]
It would be great if we can add multiple backup configurations.
- I would like to backup my HASS backups to the 'onedrive:Backup' folder. cron '0 3 * * * *'
- I would like to backup my ip cam video's to the 'onedrive:IPCamVideos' folder. cron '*/10 * * * * *'

**Comment by jcwillox** [comment]
Yeah, I was thinking the same, makes a lot of sense just haven't got around to doing it 😄

**Comment by tangli159** [comment]
> 是的，我也是这么想的，很有道理，只是还没来得及做😄

really really need support webdav backup!

**Comment by jcwillox** [comment]
This is supported as of release [2.0.0](https://github.com/jcwillox/hassio-rclone-backup/releases/tag/2.0.0) 🎉.
