### ISSUE TITLE
Exclude Mariadb

### ISSUE THREAD

**Issue by MyUncleSam** [jcwillox/hassio-rclone-backup#65]
Hi,

just wanted to ask if it is possible to exclude addons like Mariadb

**Comment by jcwillox** [comment]
You'd have to exclude them from the backup files themselves, i.e. do a partial backup and exclude the mariadb addon. If you are using rclone to copy stuff from the file system directly then rclone has a variety of options to exclude certain files, but it cant choose specific files inside an archive.
