### ISSUE TITLE
Update to "dev"

### ISSUE THREAD

**Issue by jamesmyatt** [jcwillox/hassio-rclone-backup#67]
The version number has disappeared for the update.

![image](https://github.com/jcwillox/hassio-rclone-backup/assets/1047337/b3bb32fd-b710-422e-8e72-bde9d4a125b5)

**Comment by vincegre** [comment]
yes same here and also unable to update (I'm on Hassio current version on Intel platform). I get that error when I try to update from 3.2 to 3.3:

`Échec de l'appel du service update/install. Error updating Rclone Backup: Can't install ghcr.io/jcwillox/hassio-rclone-backup/amd64:dev: 500 Server Error for http+docker://localhost/v1.44/images/create?tag=dev&fromImage=ghcr.io%2Fjcwillox%2Fhassio-rclone-backup%2Famd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")`

**Comment by jamesmyatt** [comment]
Fixed now

**Comment by jcwillox** [comment]
Ahh yes sorry was testing out a new release setup, but it was quite a bit of trial and error, everything should be back to normal now, with even better changelogs.

**Comment by vincegre** [comment]
@jcwillox Thanks a lot for the quick fix and all good now here, could update to 3.3.0 without any issues :)
