### ISSUE TITLE
[FR]: Add possibility to use 'rclone delete' jobs

### ISSUE THREAD

**Issue by ZiroNL** [jcwillox/hassio-rclone-backup#75]
### Is your feature request related to a problem? Please describe.

I use the addon for 'rclone copy' jobs, which works very nice. The destination is never cleaned up automaticly, old backup files must be deleted manualy.
It would be nice to use the addon for a 'rclone delete' job to delete backup files older then X days or months.

### Describe the solution you'd like

'rclone delete' jobs are not accepted right now. There is no source needed for this command, but the addon give's an error when it is removed or not filled in (in the config). When it is filled in with an fake one, the rclone command gives an error because of the source that is given and not needed.

**Comment by jcwillox** [comment]
I'll give this a test later but you can just provide a source and no destination, the source is what the delete command will target.

Here's and example with the `ls` command, I imagine it'll be the same for delete.

```yaml
- command: ls
  name: List Backups
  source: "hassbackup:"
```

**Comment by Cogitri** [comment]
Hej, just encountered that as well. Setting `source` to the remote destination works just fine - it does feel a bit odd though. Maybe we can add an example for that?
