### ISSUE TITLE
Ïssue with SSH keys

### ISSUE THREAD

**Issue by sondree** [jcwillox/hassio-rclone-backup#8]
Im trying to setup this addon using SSH keys to access a remote for rclone. RClone does not seem to find my SSH keys even though the path exists and the files are present. Any insights? 

From rclone.conf
```
key_file = /root/.ssh/id_rsa
pubkey_file = /root/.ssh/id_rsa.pub
```

In HAOS shell:

```
ls -lah /root/.ssh/
total 28K    
drwx------    2 root     root        4.0K Jan  8 12:08 .
drwxr-xr-x    4 root     root        4.0K Jan  3 15:54 ..
-rw-------    1 root     root        1.1K Jan  3 15:54 authorized_keys
-rw-------    1 root     root        2.5K Dec 30 16:50 id_rsa
-rw-r--r--    1 root     root         567 Dec 30 16:50 id_rsa.pub
-rw-------    1 root     root         855 Jan  8 12:08 known_hosts
```

From logs:

```
2022/01/08 16:37:00 Failed to create file system for "<redacted>": failed to read private key file: open /root/.ssh/id_rsa: no such file or directory
```

Any directory mapping I need to be aware of or user permissions required?

Thanks

**Comment by jcwillox** [comment]
That file will not be accessible or seen by the rclone container, it only mounts the config, backup, share, ssl and media directories from HA. So, if you place the cert in `/config/id_rsa` for example, it will be accessible.

HA uses docker containers so each addon has its own filesystem and is isolated from the other addons, the `/root` directory is not a mounted external directory like `/config` is and as a result is only accessible to that SSH container. I doubt it will even survive updates in that location.

**Comment by sondree** [comment]
```
ls -lah /root/
total 12K    
drwxr-xr-x    1 root     root        4.0K Jan  3 15:54 .
drwxr-xr-x    1 root     root        4.0K Jan  3 15:54 ..
lrwxrwxrwx    1 root     root          19 Dec 23 11:28 .bash_history -> /data/.bash_history
lrwxrwxrwx    1 root     root          19 Dec 23 11:28 .bash_profile -> /data/.bash_profile
lrwxrwxrwx    1 root     root          10 Dec 23 11:28 .ssh -> /data/.ssh
-rw-r--r--    1 root     root         905 Dec 23 11:28 .tmux.conf
lrwxrwxrwx    1 root     root           7 Jan  3 15:54 addons -> /addons
lrwxrwxrwx    1 root     root           7 Jan  3 15:54 backup -> /backup
lrwxrwxrwx    1 root     root           7 Jan  3 15:54 config -> /config
lrwxrwxrwx    1 root     root           6 Jan  3 15:54 share -> /share
lrwxrwxrwx    1 root     root           4 Jan  3 15:54 ssl -> /ssl
```
As you can see /root/.ssh is symlinked to /data/.ssh/. 

Moving keys to /config/.ssh/ works. For the record: 

```
key_file = /config/.ssh/id_rsa
```

Is the only required change to the rclone config file. "pubkey_file" is not required for SSH key authentication. 
(ref https://forum.rclone.org/t/sftp-ssh-error-public-key-file-is-not-a-certificate-file/22795)

Minor feature suggestion would be to add a button triggering a backup. I could not find one and I have spent a long time waiting for cron jobs to trigger. 

Thanks for the help!

**Comment by jcwillox** [comment]
Great, glad you got it working

> Minor feature suggestion would be to add a button triggering a backup. I could not find one and I have spent a long time waiting for cron jobs to trigger while debugging.

Agreed, that has been requested in #5
