### ISSUE TITLE
Manifest unknown upgrading to 3.3.2

### ISSUE THREAD

**Issue by override80** [jcwillox/hassio-rclone-backup#82]
### The problem

Hi @jcwillox ,
I'm getting this error upgrading to 3.3.2:

Failed to perform the action update/install. Error updating Rclone Backup: Can't install ghcr.io/jcwillox/hassio-rclone-backup/amd64:3.3.2: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=3.3.2&fromImage=ghcr.io%2Fjcwillox%2Fhassio-rclone-backup%2Famd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

### What version of Rclone Backup has the issue?

3.3.1

### What version of Home Assistant are you running?

2024.9

### What type of installation are you running?

Home Assistant Supervised

**Comment by jcwillox** [comment]
Yep the docker image builds didn't get triggered, running them now 👍 thanks for letting me know

**Comment by jcwillox** [comment]
It should be fixed now

**Comment by override80** [comment]
It is! Thank you!
